// Date: 06.08.2013 02:28:29
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package tektor.minecraft.chalith.model.oilPress;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelOilPressStair extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2ab;
    ModelRenderer Shape1a;
    ModelRenderer Shape2a;
    ModelRenderer Shape3;
    ModelRenderer Shape3a;
    ModelRenderer Shape2;
    ModelRenderer Shape2f;
    ModelRenderer Shape4;
    ModelRenderer Shape4a;
    ModelRenderer Shape5;
    ModelRenderer Shape5a;
    ModelRenderer Shape6;
    ModelRenderer Shape6a;
    ModelRenderer Shape6b;
    ModelRenderer Shape6c;
    ModelRenderer Shape6d;
    ModelRenderer Shape6e;
  
  public ModelOilPressStair()
  {
    textureWidth = 256;
    textureHeight = 64;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 1, 16, 2);
      Shape1.setRotationPoint(-8F, 8F, 6F);
      Shape1.setTextureSize(256, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2ab = new ModelRenderer(this, 6, 0);
      Shape2ab.addBox(0F, 0F, 0F, 1, 14, 2);
      Shape2ab.setRotationPoint(-8F, 10F, 4F);
      Shape2ab.setTextureSize(256, 64);
      Shape2ab.mirror = true;
      setRotation(Shape2ab, 0F, 0F, 0F);
      Shape1a = new ModelRenderer(this, 0, 0);
      Shape1a.addBox(0F, 0F, 0F, 1, 16, 2);
      Shape1a.setRotationPoint(7F, 8F, 6F);
      Shape1a.setTextureSize(256, 64);
      Shape1a.mirror = true;
      setRotation(Shape1a, 0F, 0F, 0F);
      Shape2a = new ModelRenderer(this, 6, 0);
      Shape2a.addBox(0F, 0F, 0F, 1, 14, 2);
      Shape2a.setRotationPoint(7F, 10F, 4F);
      Shape2a.setTextureSize(256, 64);
      Shape2a.mirror = true;
      setRotation(Shape2a, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 0);
      Shape3.addBox(0F, 0F, 0F, 1, 12, 2);
      Shape3.setRotationPoint(-8F, 12F, 2F);
      Shape3.setTextureSize(256, 64);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape3a = new ModelRenderer(this, 0, 0);
      Shape3a.addBox(0F, 0F, 0F, 1, 12, 2);
      Shape3a.setRotationPoint(7F, 12F, 2F);
      Shape3a.setTextureSize(256, 64);
      Shape3a.mirror = true;
      setRotation(Shape3a, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 0);
      Shape2.addBox(0F, 0F, 0F, 1, 10, 2);
      Shape2.setRotationPoint(-8F, 14F, 0F);
      Shape2.setTextureSize(256, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape2f = new ModelRenderer(this, 0, 0);
      Shape2f.addBox(0F, 0F, 0F, 1, 10, 2);
      Shape2f.setRotationPoint(7F, 14F, 0F);
      Shape2f.setTextureSize(256, 64);
      Shape2f.mirror = true;
      setRotation(Shape2f, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 0);
      Shape4.addBox(0F, 0F, 0F, 1, 8, 2);
      Shape4.setRotationPoint(-8F, 16F, -2F);
      Shape4.setTextureSize(256, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape4a = new ModelRenderer(this, 0, 0);
      Shape4a.addBox(0F, 0F, 0F, 1, 8, 2);
      Shape4a.setRotationPoint(7F, 16F, -2F);
      Shape4a.setTextureSize(256, 64);
      Shape4a.mirror = true;
      setRotation(Shape4a, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 0);
      Shape5.addBox(0F, 0F, 0F, 1, 6, 2);
      Shape5.setRotationPoint(-8F, 18F, -4F);
      Shape5.setTextureSize(256, 64);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape5a = new ModelRenderer(this, 0, 0);
      Shape5a.addBox(0F, 0F, 0F, 1, 6, 2);
      Shape5a.setRotationPoint(7F, 18F, -4F);
      Shape5a.setTextureSize(256, 64);
      Shape5a.mirror = true;
      setRotation(Shape5a, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 0, 0);
      Shape6.addBox(0F, 0F, 0F, 14, 1, 2);
      Shape6.setRotationPoint(-7F, 12F, 6F);
      Shape6.setTextureSize(256, 64);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape6a = new ModelRenderer(this, 0, 0);
      Shape6a.addBox(0F, 0F, 0F, 14, 1, 2);
      Shape6a.setRotationPoint(-7F, 14F, 4F);
      Shape6a.setTextureSize(256, 64);
      Shape6a.mirror = true;
      setRotation(Shape6a, 0F, 0F, 0F);
      Shape6b = new ModelRenderer(this, 0, 0);
      Shape6b.addBox(0F, 0F, 0F, 14, 1, 2);
      Shape6b.setRotationPoint(-7F, 16F, 2F);
      Shape6b.setTextureSize(256, 64);
      Shape6b.mirror = true;
      setRotation(Shape6b, 0F, 0F, 0F);
      Shape6c = new ModelRenderer(this, 0, 0);
      Shape6c.addBox(0F, 0F, 0F, 14, 1, 2);
      Shape6c.setRotationPoint(-7F, 18F, 0F);
      Shape6c.setTextureSize(256, 64);
      Shape6c.mirror = true;
      setRotation(Shape6c, 0F, 0F, 0F);
      Shape6d = new ModelRenderer(this, 0, 0);
      Shape6d.addBox(0F, 0F, 0F, 14, 1, 2);
      Shape6d.setRotationPoint(-7F, 20F, -2F);
      Shape6d.setTextureSize(256, 64);
      Shape6d.mirror = true;
      setRotation(Shape6d, 0F, 0F, 0F);
      Shape6e = new ModelRenderer(this, 0, 0);
      Shape6e.addBox(0F, 0F, 0F, 14, 1, 2);
      Shape6e.setRotationPoint(-7F, 22F, -4F);
      Shape6e.setTextureSize(256, 64);
      Shape6e.mirror = true;
      setRotation(Shape6e, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(entity,f, f1, f2, f3, f4, f5);
    Shape1.render(f5);
    Shape2ab.render(f5);
    Shape1a.render(f5);
    Shape2a.render(f5);
    Shape3.render(f5);
    Shape3a.render(f5);
    Shape2.render(f5);
    Shape2f.render(f5);
    Shape4.render(f5);
    Shape4a.render(f5);
    Shape5.render(f5);
    Shape5a.render(f5);
    Shape6.render(f5);
    Shape6a.render(f5);
    Shape6b.render(f5);
    Shape6c.render(f5);
    Shape6d.render(f5);
    Shape6e.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(Entity ent,float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, ent);
  }

}
